AWSTemplateFormatVersion: '2010-09-09'
Description:  This template deploys a eks cluster without worker nodes

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
    Default: eksworkshop
  ClusterName:
    Description: An eks cluster name
    Type: String
    Default: eksworkshop-eksctl
  ControlPlaneRoleName:
    Type: String
    Default: ControlPlaneRole
  VPC:
    Description: VPC ID for eks cluster
    Type: String
    Default: vpc-0f4bf5515382b1ea6
  WorkerNodeSubnetA:
    Type: String
    Description: Subnets for worker nodes
    Default: subnet-0d78c115d3ed3f973
  WorkerNodeSubnetB:
    Type: String
    Description: Subnets for worker nodes
    Default: subnet-0e11cdd46ff1175b8
  WorkerNodeSubnetC:
    Type: String
    Description: Subnets for worker nodes
    Default: subnet-0cd0103b186bfcf71
  WorkerNodeSubnetD:
    Type: String
    Description: Subnets for worker nodes
    Default: subnet-048988bc91b957f14
Resources:
  # Control Plane
  ControlPlaneSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Cluster communication with worker nodes
      VpcId: !Ref VPC
  ControlPlaneRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      RoleName: !Ref ControlPlaneRoleName
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        # - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
        - arn:aws:iam::aws:policy/AmazonEKSVPCResourceController
      Tags:
        - Key: Name
          Value: !Join [ "-", [ 'eksctl', !Ref ClusterName, 'cluster/ServiceRole' ]]
        - Key: alpha.eksctl.io/cluster-name
          Value: !Ref ClusterName
        - Key: alpha.eksctl.io/cluster-oidc-enabled
          Value: false
        - Key: eksctl.cluster.k8s.io/v1alpha1/cluster-name
          Value: !Ref ClusterName
        # - Key: alpha.eksctl.io/eksctl-version
        #  Value: 0.107.0
  ControlPlaneCloudWatchMetricsPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties: 
      Description: Managed Policy to attach to ControlPlane Role
      ManagedPolicyName: !Join [ "-", [ 'eksctl', !Ref ClusterName, 'cluster', 'PolicyCloudWatchMetrics' ]]
      Path: /
      PolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 'cloudwatch:PutMetricData'
            Resource: '*'
      Roles: 
        - !Ref ControlPlaneRole
  ControlPlaneELBPermissionsPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties: 
      Description: Managed Policy to attach to ControlPlane Role
      ManagedPolicyName: !Join [ "-", [ 'eksctl', !Ref ClusterName, 'cluster', 'ELBPermissions' ]]
      Path: /
      PolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 'ec2:DescribeAccountAttributes'
              - 'ec2:DescribeAddresses'
              - 'ec2:DescribeInternetGateways'
            Resource: '*'
      Roles: 
        - !Ref ControlPlaneRole
  SecretsEncryptionKey:
    Type: AWS::KMS::Key
    Properties: 
      Description: "Encryption Key for eks secrets encryption"
      KeySpec: SYMMETRIC_DEFAULT
      KeyUsage: ENCRYPT_DECRYPT
      KeyPolicy:
        Version: '2012-10-17'
        Id: key-default-1
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Join 
                - ''
                - - 'arn:aws:iam::'
                  - !Ref 'AWS::AccountId'
                  - ':root'
            Action: 'kms:*'
            Resource: '*'
      Tags: 
        - Key: Name
          Value: !Sub ${EnvironmentName} Key
  SecretsEncryptionKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/eksworkshop
      TargetKeyId: !Ref SecretsEncryptionKey
  ControlPlane:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref ClusterName
      RoleArn: 
        !GetAtt "ControlPlaneRole.Arn"
      EncryptionConfig:
        - Provider: 
            KeyArn: !GetAtt "SecretsEncryptionKey.Arn"
          Resources: 
          - secrets
      ResourcesVpcConfig:
        SecurityGroupIds:
        - !Ref ControlPlaneSecurityGroup
        SubnetIds:
        - !Ref WorkerNodeSubnetA
        - !Ref WorkerNodeSubnetB
        - !Ref WorkerNodeSubnetC
        - !Ref WorkerNodeSubnetD
      Tags:
        - Key: Name
          Value: !Join [ "-", [ !Ref EnvironmentName, !Ref ClusterName, 'cluster/ControlPlane' ]]
        - Key: alpha.eksctl.io/cluster-name
          Value: !Ref ClusterName
        - Key: eksctl.cluster.k8s.io/v1alpha1/cluster-name
          Value: !Ref ClusterName
    DependsOn: [ControlPlaneRole, ControlPlaneSecurityGroup, SecretsEncryptionKey, SecretsEncryptionKeyAlias]
Outputs:
  ControlPlane:
    Value: !Ref ControlPlane
  ControlPlaneSecurityGroup:
    Description: Security group for the cluster control plane communication with worker nodes
    Value: !Ref ControlPlaneSecurityGroup
  SecretsEncryptionKey:
    Value: !Ref SecretsEncryptionKey