AWSTemplateFormatVersion: '2010-09-09'
Description:  This template deploys a eks cluster without worker nodes

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
    Default: eksworkshop
  ControlPlaneName:
    Description: An eks cluster name
    Type: String
    Default: ekscluster-custom
  ControlPlaneRoleName:
    Type: String
    Default: ControlPlaneRole
  VPC:
    Description: VPC ID for eks cluster
    Type: String
    Default: vpc-08b124a312770499f
  WorkerNodeSubnetA:
    Type: String
    Description: Subnets for worker nodes
    Default: subnet-03cf87702a2a49d1b
  WorkerNodeSubnetB:
    Type: String
    Description: Subnets for worker nodes
    Default: subnet-0f23791acf631d95c
  WorkerNodeSubnetC:
    Type: String
    Description: Subnets for worker nodes
    Default: subnet-01df0f929b8f0527a
  WorkerNodeSubnetD:
    Type: String
    Description: Subnets for worker nodes
    Default: subnet-0267bead1b95fb2a8
Resources:
  # Control Plane
  ControlPlaneSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Cluster communication with worker nodes
      VpcId: !Ref VPC
  ControlPlaneRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      RoleName: !Ref ControlPlaneRoleName
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
  SecretsEncryptionKey:
    Type: AWS::KMS::Key
    Properties: 
      Description: "Encryption Key for eks secrets encryption"
      KeySpec: SYMMETRIC_DEFAULT
      KeyUsage: ENCRYPT_DECRYPT
      KeyPolicy:
        Version: '2012-10-17'
        Id: key-default-1
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Join 
                - ''
                - - 'arn:aws:iam::'
                  - !Ref 'AWS::AccountId'
                  - ':root'
            Action: 'kms:*'
            Resource: '*'
      Tags: 
        - Key: Name
          Value: !Sub ${EnvironmentName} Key
  SecretsEncryptionKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/eksworkshop
      TargetKeyId: !Ref SecretsEncryptionKey
  ControlPlane:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref ControlPlaneName
      RoleArn: 
        !GetAtt "ControlPlaneRole.Arn"
      EncryptionConfig:
        - Provider: 
            KeyArn: !GetAtt "SecretsEncryptionKey.Arn"
          Resources: 
          - secrets
      ResourcesVpcConfig:
        SecurityGroupIds:
        - !Ref ControlPlaneSecurityGroup
        SubnetIds:
        - !Ref WorkerNodeSubnetA
        - !Ref WorkerNodeSubnetB
        - !Ref WorkerNodeSubnetC
        - !Ref WorkerNodeSubnetD
      Tags:
        - Key: Name
          Value: !Join [ "-", [ !Ref EnvironmentName, !Ref ControlPlaneName ]]
    DependsOn: [ControlPlaneRole, ControlPlaneSecurityGroup, SecretsEncryptionKey, SecretsEncryptionKeyAlias]
Outputs:
  ControlPlaneSecurityGroup:
    Description: Security group for the cluster control plane communication with worker nodes
    Value: !Ref ControlPlaneSecurityGroup
  SecretsEncryptionKey:
    Value: !Ref SecretsEncryptionKey